apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-restored-csi-pvc
spec:
  dataSource:
    name: postgres-csi-pv-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-hostpath-sc
  resources:
    requests:
      storage: 1Gi # adjust the size as needed

